#!/bin/bash

up_file="/mnt/c/Users/sumu/up.up";

# date 
DATE=`date`;

#colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'	# also orange!
BLUE='\033[0;34m'	# not clear on a black bg
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
GRAY='\033[1;30m'	# dark gray
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
NC='\033[0m' 		# No Color

if [[ $1 == "s" ]]; then
	#echo -e "${GREEN}SEARCH FOR:${NC}"
	if [[ $2 != '' ]]; then
		echo -e "${GREEN}SEARCH RESULTS:${NC} ${CYAN}'$2'${NC}"
		cat -n "$up_file" | grep "$2"
	elif [[ $2 == '' ]]; then
		echo -e "${RED}No search term provided ${NC}"
	fi
elif [[ $1 == "a" ]]; then
	#echo -e "Add"
	if [[ $2 != '' ]]; then
		echo -e "${GREEN}Add: ${CYAN}'$2' ${YELLOW}to the Database${NC}"
		if [[ -e "$up_file" ]]; then
			echo "$2|$DATE" >> "$up_file"
			echo -e "${GREEN}Verification: ${YELLOW}Showing the latest addition to the database${NC}"
			tail -n 1 $up_file
		else
			echo -e "${RED}File does not exist or is not writable${NC}"
			echo -e "${GREEN}Please create file ${CYAN}'up.up'${NC} in the directory above ${BROWN}'$PWD' (Current Directory) $NC"
			echo -e "${GREEN}File 'up.up' should be writable by ${WHITE}${USER} ${NC}"
			echo -e "${RED}Do not create ${CYAN}'up.up' ${RED}in the current directory:${CYAN}'$PWD' ${RED}or a/any publicly accessible directory ${NC}"
		fi
	fi
else
	echo -e "${RED}No flag(s) or unknown flag(s): ${BROWN}$1 $2${NC}";
	echo -e "${PURPLE}USAGE: /home/a1z/up/up.sh search term ${NC}"
fi
